version_final/ecuaRefills2/Controllers/CiudadesController.cs
using ecuaRefills2.Data;
using ecuaRefills2.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ecuaRefills2.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class CiudadesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CiudadesController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> CiudadIndex( string searchString)
        {
            var applicationDbContext = _context.Ciudad.OrderBy(s => s.Nombre).Include(c => c.Provincia);
            var ciudades = from s in _context.Ciudad
                           select s;
            //Si el string no es nulo o no esta vacio se realiza la consulta.
            if (!String.IsNullOrEmpty(searchString))
            {
                ciudades = ciudades.OrderBy(s => s.Nombre).Include(c => c.Provincia).Where(s => s.Nombre.Contains(searchString) || s.Provincia.Nombre.Contains(searchString));
                return View(await ciudades.ToListAsync());
            }
            return View(await applicationDbContext.ToListAsync());
        }
        public IActionResult CrearCiudad()
        {
            ViewBag.Provincias = new SelectList(_context.Provincia.OrderBy(x => x.Nombre), "ProvinciaId", "Nombre");
            return View();
        }

        [HttpPost]
        //Si algo sale mal agregar el Bind
        public IActionResult CrearCiudad(Ciudad ciudad)
        {
            //se agrego la condicion y el view data.
            if (ModelState.IsValid)
            {
                _context.Ciudad.Add(ciudad);
                _context.SaveChanges();
                TempData["mensaje"] = "La ciudad se ha creado correctamente.";
                return RedirectToAction("CiudadIndex");
            }
            ViewBag.Provincias = new SelectList(_context.Provincia.OrderBy(x => x.Nombre), "ProvinciaId", "Nombre", ciudad.ProvinciaId);
            return View(ciudad);
        }

        public async Task<IActionResult> DetalleCiudad(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ciudad = await _context.Ciudad
                .Include(c => c.Provincia)
                .FirstOrDefaultAsync(m => m.CiudadId == id);
            if (ciudad == null)
            {
                return NotFound();
            }

            return View(ciudad);
        }

        public async Task<IActionResult> EditarCiudad(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ciudad = await _context.Ciudad.FindAsync(id);
            if (ciudad == null)
            {
                return NotFound();
            }
            ViewBag.Provincias = new SelectList(_context.Provincia.OrderBy(x => x.Nombre), "ProvinciaId", "Nombre", ciudad.ProvinciaId);
            return View(ciudad);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditarCiudad(int id, [Bind("CiudadId,Nombre,ProvinciaId")] Ciudad ciudad)
        {
            if (id != ciudad.CiudadId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ciudad);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CiudadExists(ciudad.CiudadId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["mensaje"] = "La ciudad se ha actualizado correctamente.";
                return RedirectToAction(nameof(CiudadIndex));
            }
            ViewBag.Provincias = new SelectList(_context.Provincia.OrderBy(x => x.Nombre), "ProvinciaId", "Nombre", ciudad.ProvinciaId);
            return View(ciudad);
        }


        // GET: Ciudades/Delete/5
        public async Task<IActionResult> BorrarCiudad(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ciudad = await _context.Ciudad
                .Include(c => c.Provincia)
                .FirstOrDefaultAsync(m => m.CiudadId == id);
            if (ciudad == null)
            {
                return NotFound();
            }

            return View(ciudad);
        }

        // POST: Ciudades/Delete/5
        [HttpPost, ActionName("BorrarCiudad")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmarBorrar(int id)
        {
            var ciudad = await _context.Ciudad.FindAsync(id);
            _context.Ciudad.Remove(ciudad);
            await _context.SaveChangesAsync();
            TempData["mensaje"] = "La ciudad se ha eliminado correctamente.";
            return RedirectToAction(nameof(CiudadIndex));
        }

        //Revisar si una ciudad existe.
        private bool CiudadExists(int id)
        {
            return _context.Ciudad.Any(e => e.CiudadId == id);
        }


    }
}

version_final/ecuaRefills2/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ecuaRefills2.Data;
using ecuaRefills2.Entities;
using Microsoft.AspNetCore.Authorization;

namespace ecuaRefills2.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clientes

        public async Task<IActionResult> Index(string searchString)
        {
            var applicationDbContext = _context.Cliente.Include(c => c.Ciudad).OrderBy(x => x.Nombre);

            var clientes = from s in _context.Cliente
                           select s;
            //Si el string no es nulo o no esta vacio se realiza la consulta.
            if (!String.IsNullOrEmpty(searchString))
            {
                clientes = clientes.Include(c => c.Ciudad).Where(s => s.Nombre.Contains(searchString) || s.Cedula.Contains(searchString)
                || s.CorreoElectronico.Contains(searchString) || s.Ciudad.Nombre.Contains(searchString)).OrderBy(x => x.Nombre);
                return View(await clientes.ToListAsync());
            }

            return View(await applicationDbContext.ToListAsync());

        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .Include(c => c.Ciudad)
                .FirstOrDefaultAsync(m => m.ClienteId == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        [HttpGet]
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            ViewBag.Provincias = new SelectList(_context.Provincia.OrderBy(x => x.Nombre), "ProvinciaId", "Nombre");
            return View();
        }


        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrador")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClienteId,Cedula,Nombre,CorreoElectronico,Telefono,CiudadId")] Cliente cliente, Cliente model)
        {
            //if (ModelState.IsValid)
            //{
            //    _context.Add(cliente);
            //    await _context.SaveChangesAsync();
            //    TempData["mensaje"] = "El cliente se ha creado correctamente.";
            //    return RedirectToAction(nameof(Index));
            //}
            //ViewData["CiudadId"] = new SelectList(_context.Ciudad, "CiudadId", "Nombre", cliente.CiudadId);
            //return View(cliente);
            try
            {
                var cedulaExiste = _context.Cliente.FirstOrDefault(m => m.Cedula == model.Cedula);

                if (cedulaExiste == null)
                {
                    if (ModelState.IsValid)
                    {
                        _context.Add(cliente);
                        await _context.SaveChangesAsync();
                        TempData["mensaje"] = "El cliente se ha creado correctamente.";
                        return RedirectToAction(nameof(Index));
                    }
                }
                else
                {
                    TempData["CedulaExiste"] = "No se pudo insertar el cliente, El registro ya existe.";
                    return RedirectToAction(nameof(Index));
                }


            }
            catch (Exception e)
            {
                TempData["error"] = e.ToString();
                ViewBag.error = TempData["error"].ToString();
            }
            ViewData["CiudadId"] = new SelectList(_context.Ciudad.OrderBy(x => x.Nombre), "CiudadId", "Nombre", cliente.CiudadId);
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            ViewBag.Provincias = new SelectList(_context.Provincia.OrderBy(x => x.Nombre), "ProvinciaId", "Nombre");
            ViewData["CiudadId"] = new SelectList(_context.Ciudad.OrderBy(x => x.Nombre), "CiudadId", "Nombre", cliente.CiudadId);
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrador")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClienteId,Cedula,Nombre,CorreoElectronico,Telefono,CiudadId")] Cliente cliente)
        {
            if (id != cliente.ClienteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.ClienteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["mensaje"] = "El cliente se ha actualizado correctamente.";
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Provincias = new SelectList(_context.Provincia.OrderBy(x => x.Nombre), "ProvinciaId", "Nombre");
            ViewData["CiudadId"] = new SelectList(_context.Ciudad.OrderBy(x => x.Nombre), "CiudadId", "Nombre", cliente.CiudadId);
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .Include(c => c.Ciudad)
                .FirstOrDefaultAsync(m => m.ClienteId == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Cliente.FindAsync(id);
            _context.Cliente.Remove(cliente);
            await _context.SaveChangesAsync();
            TempData["mensaje"] = "El cliente se ha eliminado correctamente";
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Cliente.Any(e => e.ClienteId == id);
        }


        public JsonResult LocalizarCiudad(int Id)
        {

            var ciudad = _context.Ciudad.Where(x => x.ProvinciaId == Id).ToList();
            return Json(new SelectList(ciudad, "CiudadId", "Nombre"));
        }

    }
}

version_final/ecuaRefills2/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ecuaRefills2.Areas.Identity.Data.Usuario> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ecuaRefills2</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/general_cliente.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow menu-inicial " style="background-color: #1b2030 ">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/Imagenes/ecua.png" width="150" height="60" class="d-inline-block align-top" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Administrador"))
                        {
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                    </li>

                                    <li class="nav-item dropdown">
                                        <a class="nav-link text-light dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Administración
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                            <a class="dropdown-item" asp-controller="Administration"
                                               asp-action="ListUsers">Usuarios</a>
                                            <a class="dropdown-item" asp-controller="Administration"
                                               asp-action="ListRoles">Roles</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Ciudades"
                                               asp-action="CiudadIndex">Ciudad</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Provincias"
                                               asp-action="ProvinciaIndex">Provincia</a>

                                        </div>
                                    </li>}
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Visitante"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                            </li>

                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="padding-top: 120px">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EcuaRefills
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>