version_final/ecuaRefills2/Entities/Provincia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ecuaRefills2.Entities
{
    public class Provincia
    {
        public int ProvinciaId { get; set; }
        public string Nombre { get; set; }
        public ICollection<Ciudad> Ciudades { get; set; }
    }
}

version_final/ecuaRefills2/Controllers/ProvinciasController.cs
using ecuaRefills2.Data;
using ecuaRefills2.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ecuaRefills2.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ProvinciasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProvinciasController(ApplicationDbContext context)
        {
            _context = context;
        }

        
        public IActionResult ProvinciaIndex( string searchString)
        {
            var provincias = _context.Provincia.OrderBy(s => s.Nombre);
            var provincia = from s in _context.Provincia
                         select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                provincia = provincia.OrderBy(s => s.Nombre).Where(s => s.Nombre.Contains(searchString));
                return View( provincia.ToList());
            }

            return View( provincias.ToList());
        }
        [HttpGet]
        public IActionResult CrearProvincia()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CrearProvincia(Provincia provincia)
        {
            if (ModelState.IsValid)
            {
                _context.Provincia.Add(provincia);
                _context.SaveChanges();
                TempData["mensaje"] = "La provincia se ha agregado correctamente.";
                return RedirectToAction("ProvinciaIndex");
            }
            return View(provincia);
        }

        // GET: Provincias/Details/5
        public async Task<IActionResult> DetalleProvincia(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provincia = await _context.Provincia
                .FirstOrDefaultAsync(m => m.ProvinciaId == id);
            if (provincia == null)
            {
                return NotFound();
            }

            return View(provincia);
        }


        // GET: Provincias/Edit/5
        public async Task<IActionResult> EditarProvincia(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provincia = await _context.Provincia.FindAsync(id);
            if (provincia == null)
            {
                return NotFound();
            }
            return View(provincia);
        }

        // POST: Provincias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditarProvincia(int id, [Bind("ProvinciaId,Nombre")] Provincia provincia)
        {
            if (id != provincia.ProvinciaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(provincia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProvinciaExists(provincia.ProvinciaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["mensaje"] = "La provincia se ha actualizado correctamente.";
                return RedirectToAction(nameof(ProvinciaIndex));
            }
            return View(provincia);
        }

        // GET: Provincias/Delete/5
        public async Task<IActionResult> BorrarProvincia(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provincia = await _context.Provincia
                .FirstOrDefaultAsync(m => m.ProvinciaId == id);
            if (provincia == null)
            {
                return NotFound();
            }

            return View(provincia);
        }

        // POST: Provincias/Delete/5
        [HttpPost, ActionName("BorrarProvincia")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmacionBorrarProvincia(int id)
        {
            var provincia = await _context.Provincia.FindAsync(id);
            _context.Provincia.Remove(provincia);
            await _context.SaveChangesAsync();
            TempData["mensaje"] = "La provincia se ha eliminado correctamente.";
            return RedirectToAction(nameof(ProvinciaIndex));
        }

        private bool ProvinciaExists(int id)
        {
            return _context.Provincia.Any(e => e.ProvinciaId == id);
        }

    }
}

version_final/ecuaRefills2/Views/Provincias/BorrarProvincia.cshtml
@model ecuaRefills2.Entities.Provincia

@{
    ViewData["Title"] = "BorrarProvincia";
}

<div class="row">
    <div class="col-md-10">
        <h1>Provincias - Borrar</h1>
    </div>
    <div class="col-md-2">
        <a asp-action="ProvinciaIndex" class="btn btn-primary float-right" style=" margin: 2px; border-radius:4px;">Regresar</a>
    </div>
</div>
<hr />
<h3  class="text-danger">¿Está seguro de eliminar la siguiente provincia?</h3>
<br />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>

    <form asp-action="BorrarProvincia">
        <input type="hidden" asp-for="ProvinciaId" />
        <input type="submit" value="Eliminar Provincia" style="margin: 2px; border-radius: 4px; margin-top: 60px;" class="btn btn-danger" />
    </form>
</div>

version_final/ecuaRefills2/Views/Provincias/CrearProvincia.cshtml
@model ecuaRefills2.Entities.Provincia

@{
    ViewData["Title"] = "CrearProvincia";
}

<div class="row">
    <div class="col-md-10">
        <h1>Nueva Provincia</h1>
    </div>
    <div class="col-md-2">
        <a asp-action="ProvinciaIndex" class="btn btn-primary float-right" style=" margin: 2px; border-radius:4px;">Regresar</a>
    </div>
</div>
<hr />
<br />
<div class="row">
    <div class="col-md-12">
        <form asp-action="CrearProvincia">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <div class="input-group mb-2">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="bi bi-building"></i></div>
                    </div>
                    <input asp-for="Nombre" class="form-control" required />
                </div>
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-12">
                <input type="submit" value="Añadir Provincia" style="margin: 2px; border-radius: 4px; margin-top: 60px;" class="btn btn-info float-right" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

version_final/ecuaRefills2/Views/Provincias/DetalleProvincia.cshtml
@model ecuaRefills2.Entities.Provincia

@{
    ViewData["Title"] = "DetalleProvincia";
}

<div class="row">
    <div class="col-md-10">
        <h1>Provincia - Detalle</h1>
    </div>
    <div class="col-md-2">
        <a asp-action="ProvinciaIndex" class="btn btn-primary float-right" style=" margin: 2px; border-radius:4px;">Regresar</a>
    </div>
</div>
<hr />
<br />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="EditarProvincia" asp-route-id="@Model.ProvinciaId" style="margin: 2px; border-radius: 4px; margin-top: 60px;" class="btn btn-info">Editar</a>

</div>

version_final/ecuaRefills2/Views/Provincias/EditarProvincia.cshtml
@model ecuaRefills2.Entities.Provincia

@{
    ViewData["Title"] = "Editar Provincia";
}

<div class="row">
    <div class="col-md-10">
        <h1>Editar Provincia</h1>
    </div>
    <div class="col-md-2">
        <a asp-action="ProvinciaIndex" class="btn btn-primary float-right" style=" margin: 2px; border-radius:4px;">Regresar</a>
    </div>
</div>
<hr />
<br />
<div class="row">
    <div class="col-md-12">
        <form asp-action="EditarProvincia">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProvinciaId" />
            <div class="form-group ">
                <label asp-for="Nombre" class="control-label"></label>
                <div class="input-group mb-2">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="bi bi-building"></i></div>
                    </div>
                    <input asp-for="Nombre" class="form-control" />
                </div>
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-12">
                <input type="submit" value="Guardar" style="margin: 2px; border-radius: 4px; margin-top: 80px;" class="btn btn-info float-right" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

version_final/ecuaRefills2/Views/Provincias/ProvinciaIndex.cshtml
@model IEnumerable<ecuaRefills2.Entities.Provincia>

@{
    ViewData["Title"] = "ProvinciaIndex";
}
<div>
    <div class="row">
        <div class="col-10">
            <h1>PROVINCIAS</h1>
        </div>
        <div class="col-2">
            <a asp-action="CrearProvincia" class="btn btn-primary float-right">Nueva Provincia</a>
        </div>
    </div>
    <hr />
    <div>
        @if (TempData["mensaje"] != null)
        {
            <div class="alert alert-success alert-dimissible fade show" role="alert">
                @TempData["mensaje"]
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        <form asp-controller="Provincias" asp-action="ProvinciaIndex">
            <div class="form-row">
                <div class="col-9">
                    <input type="text" name="SearchString" class="form-control" placeholder="Nombre de la provincia">
                </div>
                <div class="col-1">
                    <input type="submit" value="Filtrar" class="form-control btn btn-info">
                </div>
            </div>
        </form>
        <br />
        <br />
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Nombre)
                        </th>
                        <th class="text-center">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td class="text-center">
                                <a asp-action="EditarProvincia" asp-route-id="@item.ProvinciaId"><img src="~/Imagenes/editar.png" height="30" width="30" /></a>
                                <a asp-action="DetalleProvincia" asp-route-id="@item.ProvinciaId"><img src="~/Imagenes/ver.png" height="30" width="30" /></a>
                                <a asp-action="BorrarProvincia" asp-route-id="@item.ProvinciaId"><img src="~/Imagenes/eliminar.png" height="30" width="30" /></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>